version: "3.9"
services:

  btc-docker:
    build:       
      context: .
      shm_size: '2gb'
    image: btc-docker:latest
    ports:
      - "${HOST_PORT:-8333}:${CONTAINER_PORT:-8333}"
      - "127.0.0.1:${HOST_PORT:-8332}:${CONTAINER_PORT:-8332}"
    environment:
      - TZ=${CONTAINER_TZ:-America/New_York}
    volumes:
      - ./data:/var/lib/bitcoind:rw
    networks:
      - bitcoind
    stop_grace_period: 3s

    # NOTE: see docker-compose.override.yml or specify additional override files for container:host ports 
    # and other runtime overrides.

networks:
  bitcoind:
volumes:
   data:
